const mongoose=require('mongoose')
const candidateModel=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    mobileNo:{
        type:String,
        required:true
    },
    dateOfBirth:{
        type:Date,
        required:true
    },
    workExperience:{
        type:String,
        default:""
    },
    resumeTitle:{
        type:String,
        required:true
    },
    currentLocation:{
        type:String,
        required:true
    },
    postalAddress:{
        type:String,
        required:true
    },
    currentEmployer:{
        type:String,
        required:true
    },
    currentDesignation:{
        type:String,
        required:true
    },
},{
    timestamps:true
})

const Candidate=mongoose.model('Candidate',candidateModel)
module.exports=Candidate